### ISSUE TITLE
👩‍🌾 Regression introduced in packaging by enabling `rosbag2_performance_benchmarking` 

### ISSUE THREAD

**Issue by claraberendsen** [ros2/rosbag2#2103]
## Description
Packaging windows and packaging RHEL started failing with the inclusion of `rosbag2_performance_benchmarking` in #2093.
There are two distinct errors that I will report on the same issue since they relate to the same PR.
### Packaging Windows

Reference build: https://ci.ros2.org/job/packaging_windows/3694/

This is a consistent issue and related to the length limit of a filenames in Windows on `rosbag2_performance_benchmarking_msgs`. The error is
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(382,5): error MSB3491: Could not write lines to file "rosbag2_performance_benchmarking_msgs__rosidl_typesupport_introspection_cpp.dir\RelWithDebInfo\rosbag2_.A688C7ED.tlog\rosbag2_performance_benchmarking_msgs__rosidl_typesupport_introspection_cpp.lastbuildstate". Path: rosbag2_performance_benchmarking_msgs__rosidl_typesupport_introspection_cpp.dir\RelWithDebInfo\rosbag2_.A688C7ED.tlog\rosbag2_performance_benchmarking_msgs__rosidl_typesupport_introspection_cpp.lastbuildstate exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [C:\ci\ws\build\rosbag2_performance_benchmarking_msgs\rosbag2_performance_benchmarking_msgs__rosidl_typesupport_introspection_cpp.vcx
```

### Packaging RHEL

Reference build: https://ci.ros2.org/job/packaging_linux-rhel/2394/

It seems to be inconsistent (there is at least 1 green since July 25th). The error when failing is of out of memory possibly due to linking two big pieces of code. 

```
07:13:55 [ 69%] Linking CXX executable results_writer
07:13:55 [ 69%] Built target results_writer
07:13:55 [ 76%] Building CXX object CMakeFiles/benchmark_publishers.dir/src/benchmark_publishers.cpp.o
07:13:55 c++: fatal error: Killed signal terminated program cc1plus
07:13:55 compilation terminated.
07:13:55 gmake[2]: *** [CMakeFiles/benchmark_publishers.dir/build.make:76: CMakeFiles/benchmark_publishers.dir/src/benchmark_publishers.cpp.o] Error 1
07:13:55 gmake[1]: *** [CMakeFiles/Makefile2:167: CMakeFiles/benchmark_publishers.dir/all] Error 2
07:13:55 gmake: *** [Makefile:146: all] Error 2
```
### Expected Behavior
Expected both jobs to pass

### Actual Behavior
Jobs fail

## System (please complete the following information)
 - OS: RHEL + Windows
 - ROS 2 Distro: Rolling

**Comment by MichaelOrlov** [comment]
cc: @mjcarroll How to proceed with these issues?
The CI was green when I was merging changes.

**Comment by MichaelOrlov** [comment]
For the long path issue on Windows we probably can move the `rosbag2_performance_benchmarking` and `rosbag2_performance_benchmarking_msgs` packages out of the upper level `rosbag2_performance` subfolder.

However, I have no idea how to fix out of memory issue in Linker on the RHEL build.

**Comment by mjcarroll** [comment]
@claraberendsen shouldn't we be able to enable long paths on Windows?  This is what we advise users to do in the Windows installation.

**Comment by mjcarroll** [comment]
> However, I have no idea how to fix out of memory issue in Linker on the RHEL build.

In this case, it looks like we were also building the rviz_default_plugins concurrently, I wonder if that contributed to running out of memory?  I would hate to have to use the sequential executor here.

**Comment by MichaelOrlov** [comment]
In the `benchmark_publishers` linking section not much actually 
```cmake
target_link_libraries(benchmark_publishers
  rclcpp::rclcpp
  rosbag2_storage::rosbag2_storage
  ${rosbag2_performance_benchmarking_msgs_TARGETS}
  ${sensor_msgs_TARGETS}
  yaml-cpp::yaml-cpp
)
```
In the `rosbag2_performance_benchmarking_msgs` is the only one very simple `ByteArray.msg`
```txt
byte[]            data          # array of data
```

**Comment by claraberendsen** [comment]
> @claraberendsen shouldn't we be able to enable long paths on Windows?  This is what we advise users to do in the Windows installation.

I think so, I can take a look to see if that is part of our recipes for provisioning and if not see to add it and test.

**Comment by claraberendsen** [comment]
Update from today, the issue with RHEL is affecting `aarch64` packaging job as well: See https://ci.ros2.org/job/packaging_linux-aarch64/3245.

**Comment by claraberendsen** [comment]
I linked this PR with the fixes keyword and it automatically got closed.
This should be fixed on the Windows side with that PR.
But the issue with `rviz_default_plugins` is still ocurring. @mjcarroll let me know if you prefer to close this one and open a new one on rviz instead.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **Open Robotics Discourse**. There might be relevant details there:

https://discourse.openrobotics.org/t/ros-pmc-minutes-for-august-5-2025/49439/1

**Comment by cottsay** [comment]
Attempted mitigation: https://github.com/ros2/ci/pull/822

**Comment by ros-discourse** [comment]
This issue has been mentioned on **Open Robotics Discourse**. There might be relevant details there:

https://discourse.openrobotics.org/t/ros-pmc-minutes-for-august-12-2025/49548/1

**Comment by Crola1702** [comment]
@mjcarroll @cottsay I still see error where `rosbag2_performance_benchmarking` builds at the same time as `rviz_default_plugins`:

```
05:43:01 --- stderr: rosbag2_performance_benchmarking
05:43:01 c++: fatal error: Killed signal terminated program cc1plus
05:43:01 compilation terminated.
...
05:50:48 Failed   <<< rosbag2_performance_benchmarking [1min 32s, exited with code 2]
05:50:48 Aborted  <<< rviz_default_plugins [14min 20s]
```

See: https://ci.ros2.org/view/packaging/job/packaging_linux-rhel/2425/consoleFull

**Comment by christophebedard** [comment]
I think the fix from https://github.com/ros2/ci/pull/822 didn't work. I just saw this in the logs of one of my CI jobs:

```
11:20:09 [0.398s] WARNING:colcon.colcon_metadata.package_discovery.colcon_meta:Skipping metadata file '/home/jenkins-agent/workspace/ci_linux-aarch64/ws/colcon.meta' since it failed to parse: mapping values are not allowed here
11:20:09   in "<unicode string>", line 1, column 29:
11:20:09     names:  rviz_default_plugins:    build-dependencies:      -  ... 
```

https://ci.ros2.org/job/ci_linux-aarch64/18711/consoleFull#console-section-323

**Comment by cottsay** [comment]
Oof, I think maybe the newlines got dropped when I embedded it in the Dockerfile...

**Comment by MichaelOrlov** [comment]
- Closing as fixed. Feel free to reopen if you still see that this issue reproduces on CI.
